[start]
command:/usr/local/etc/rc.d/stunmesh start
parameters:
type:script
message:Starting STUNMESH service

[stop]
command:/usr/local/etc/rc.d/stunmesh stop
parameters:
type:script
message:Stopping STUNMESH service

[restart]
command:/usr/local/etc/rc.d/stunmesh restart
parameters:
type:script
message:Restarting STUNMESH service

[status]
command:/usr/local/etc/rc.d/stunmesh status;exit 0
parameters:
type:script_output
message:Probing STUNMESH service
